---
- name: "Get facts"
  hosts: vendors-all
  connection: local
  gather_facts: no
  tasks:

    - name: Get facts from device
      napalm_get_facts:
        hostname: "{{ credentials.hostname }}"
        username: "{{ credentials.username }}"
        password: "{{ credentials.password }}"
        dev_os: "{{ credentials.driver }}"
        filter: ['facts']
      register: result

    - name: print data
      debug: 
        var=result